import { promises as fs } from "fs";
import { resolve, basename } from "path";

const ICONS_DIR = resolve(__dirname, "../../extension/icons/products");
const OUTPUT_FILE = resolve(__dirname, "../src/config/icon-categories.ts");

async function generateProductCategories() {
    try {
        const files = await fs.readdir(ICONS_DIR);
        const categories = files
            .filter((file) => file.endsWith(".png"))
            .map((file) => basename(file, ".png"))
            .sort(); // Sort alphabetically for consistency

        const content = `// This file is auto-generated by a build script. Do not edit manually.
// See server/scripts/generate-icon-categories.ts for source.

export const ICON_CATEGORIES = [
${categories.map((cat) => `    "${cat}",`).join("\n")}
];

export type IconCategory = typeof ICON_CATEGORIES[number];
`;

        await fs.writeFile(OUTPUT_FILE, content, "utf-8");
        console.log(
            `[BUILD] Successfully generated ${OUTPUT_FILE} with ${categories.length} categories.`,
        );
    } catch (error) {
        console.error(`[BUILD] Error generating product categories:`, error);
        process.exit(1); // Exit with error code
    }
}

generateProductCategories();
